kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: {{ include "team-video.fullname" . }}-web
  labels:
    app: {{ include "team-video.fullname" . }}-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "team-video.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "team-video.fullname" . }}-web
      annotations:
        timestamp: "{{ now | unixEpoch }}"
    spec:
      containers:
       - name: web
         image: jitsi/web
         imagePullPolicy: {{ .Values.app.pullpolicy }}
         ports:
          - name: web
            containerPort: 80
        {{if .Values.hideWelcomePage}}
         lifecycle:
           postStart:
             exec:
               command: ['/bin/bash', '-c', 'sleep 60; sed -i "s/enableWelcomePage: true,/enableWelcomePage: false,/g" /config/config.js']
        {{end}}
         env:
          {{ if .Values.auth.enabled}}
          - name: ENABLE_AUTH
            value: "1"
            {{ if .Values.auth.guests}}
          - name: ENABLE_GUESTS
            value: "1"
            {{end}}
            {{ if .Values.auth.ldapauthmethod}}
          - name: LDAP_AUTH_METHOD
            value: {{ .Values.auth.ldapauthmethod}}
            {{end}}
            {{ if .Values.auth.ldapurl }}
          - name: LDAP_URL
            value: {{ .Values.auth.ldapurl }}
            {{end}}
            {{ if .Values.auth.ldapusetls }}
          - name: LDAP_USE_TLS
            value: {{ .Values.auth.ldapusetls }}
            {{end}}
            {{ if .Values.auth.ldapstarttls }}
          - name: LDAP_START_TLS
            value: {{ .Values.auth.ldapstarttls }}
            {{end}}
            {{ if .Values.auth.ldaptlscacertfile }}
          - name: LDAP_TLS_CACERT_FILE
            value: {{ .Values.auth.ldaptlscacertfile }}
            {{end}}
            {{ if .Values.auth.ldaptlscacertdir }}
          - name: LDAP_TLS_CACERT_DIR
            value: {{ .Values.auth.ldaptlscacertdir }}
            {{end}}
            {{ if .Values.auth.ldapcheckpeer }}
          - name: LDAP_TLS_CHECK_PEER
            value: {{ .Values.auth.ldapcheckpeer }}
            {{end}}
            {{ if .Values.auth.ldapbase }}
          - name: LDAP_BASE
            value: {{ .Values.auth.ldapbase }}
            {{end}}
            {{ if .Values.auth.ldapbinddn }}
          - name: LDAP_BINDDN
            value: {{ .Values.auth.ldapbinddn }}
            {{end}}
            {{ if .Values.auth.ldapbindpw }}
          - name: LDAP_BINDPW
            value: {{ .Values.auth.ldapbindpw }}
            {{end}}
            {{ if .Values.auth.ldapfilter }}
          - name: LDAP_FILTER
            value: {{ .Values.auth.ldapfilter }}
            {{end}}
            {{ if .Values.auth.ldapversion }}
          - name:  LDAP_VERSION
            value: {{ .Values.auth.ldapversion }}
            {{end}}
          {{end}}
          - name: JICOFO_AUTH_USER
            value: focus
          - name: XMPP_DOMAIN
            value: {{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: XMPP_AUTH_DOMAIN
            value: auth.{{ .Values.app.name }}.{{ .Values.app.domain }}
            {{ if .Values.auth.guests}}
          - name: XMPP_GUEST_DOMAIN
            value: guest.{{ .Values.app.name }}.{{ .Values.app.domain }}
            {{end}}
          - name: XMPP_BOSH_URL_BASE
            value: http://{{ include "team-video.fullname" . }}-prosody:5280
          - name: XMPP_MUC_DOMAIN
            value: muc.{{ .Values.app.name }}.{{ .Values.app.domain }}
          - name: TZ
            value: Europe/Paris
          - name: PUBLIC_URL
            value: "https://{{ .Values.app.name }}.{{ .Values.app.domain }}"
          - name: SHOW_JITSI_WATERMARK
            value: "false"
          - name: SHOW_WATERMARK_FOR_GUESTS
            value: "false"