apiVersion: v1
kind: Service
metadata:
  name: {{ include "team-share.fullname" . }}-rc
  namespace: default
spec:
  ports:
    - protocol: TCP
      name: web
      port: 8080
      targetPort: 8080
  selector:
    app: {{ include "team-share.fullname" . }}-rc
